package frontend;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import backend.Denklem;

import javax.swing.*;
import java.awt.*;
import java.util.Random;

/**
 *
 * @author baselkelziye
 */
public class TestPage extends javax.swing.JFrame {

    /**
     * Creates new form TestPage
     */
    public TestPage() {

        Random rand = new Random();
        int lengthOfTheEquation = rand.nextInt(3) + 7;


        Denklem denklem1 = new Denklem();
        denklem1.infix2Postfix(denklem1.getDenklem());

        while(lengthOfTheEquation != denklem1.isAllowed(lengthOfTheEquation)){
            denklem1 = new Denklem();
            denklem1.infix2Postfix(denklem1.getDenklem());
        }
        setLocationRelativeTo(null);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setTitle("Test Ekranı");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width/2 - getWidth()/2, screenSize.height/2- getHeight()/2);


        equationLabel.setText(Denklem.getFinalEquation());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        equationLabel = new javax.swing.JLabel();
        yenidenUretButonu = new javax.swing.JButton();
        geriDonButonu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 254, 255));

        jPanel2.setBackground(new java.awt.Color(246, 250, 255));

        equationLabel.setFont(new java.awt.Font("SansSerif", Font.BOLD, 16)); // NOI18N
        equationLabel.setText("jLabel1");

     //   yenidenUretButonu.setBorderPainted(false);
     //   yenidenUretButonu.setOpaque(true);
        yenidenUretButonu.setBackground(new java.awt.Color(51, 67, 100));
        yenidenUretButonu.setFont(new java.awt.Font("SansSerif", Font.BOLD, 16)); // NOI18N
        yenidenUretButonu.setForeground(new java.awt.Color(244, 244, 244));
        yenidenUretButonu.setText("Yeniden Üret");
        yenidenUretButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenidenUretButonuActionPerformed(evt);
            }
        });


    //    geriDonButonu.setBorderPainted(false);
     //   geriDonButonu.setOpaque(true);
        geriDonButonu.setBackground(new java.awt.Color(51, 67, 100));
        geriDonButonu.setFont(new java.awt.Font("SansSerif", Font.BOLD, 16)); // NOI18N
        geriDonButonu.setForeground(new java.awt.Color(244, 244, 244));
        geriDonButonu.setText("Geri Dön");
        geriDonButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonButonuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", Font.BOLD, 14)); // NOI18N
        jLabel1.setText("2- 20011629 Barış Bakım - 20011906 Basel Kelziye");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(geriDonButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(yenidenUretButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(equationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(equationLabel)
                .addGap(54, 54, 54)
                .addComponent(yenidenUretButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriDonButonu, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yenidenUretButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenidenUretButonuActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        int lengthOfTheEquation = rand.nextInt(3) + 7;


        Denklem denklem1 = new Denklem();
        denklem1.infix2Postfix(denklem1.getDenklem());

        while(lengthOfTheEquation != denklem1.isAllowed(lengthOfTheEquation)){
            denklem1 = new Denklem();
            denklem1.infix2Postfix(denklem1.getDenklem());
        }
        equationLabel.setText(Denklem.getFinalEquation());

    }//GEN-LAST:event_yenidenUretButonuActionPerformed

    private void geriDonButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonButonuActionPerformed
        // TODO add your handling code here:
        dispose();


        MenuPage menuPage =  new MenuPage(new Istatistikler());
        menuPage.setVisible(true);
    }//GEN-LAST:event_geriDonButonuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equationLabel;
    private javax.swing.JButton geriDonButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton yenidenUretButonu;
    // End of variables declaration//GEN-END:variables
}
